[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mr_opentab"
version = "1.0.0"
description = "Command to use window.open in the browser"
authors = [{name = "Assistant"}]
